### ISSUE TITLE
A building issue with lunch

### ISSUE THREAD

**Issue by viscropst** [nitrogen-project/android_build_make#1]
While I type the 'lunch' it's shows ``make: *** build/target/board/generic: is a dictionary. Stop ``

**Comment by nitin1438** [comment]
@viscropst did you find any solution for this? 

Nitin

**Comment by nitin1438** [comment]
Solved with this commit:
https://github.com/nitrogen-os-devices/android_device_google_taimen/commit/dce7cf5c154ec6c4d2f68349e18c20f5a31b4451

**Comment by viscropst** [comment]
Okey,Thanks.
